namespace Domain.Models.Account
{
    /// <summary>
    /// Model to hold the data fo password confirmation
    /// </summary>
    public class ForgetPasswordConfirmationModel
    {
        /// <summary>
        /// Unique username
        /// </summary>
        public string Username { get; set; }
        /// <summary>
        /// One time password generated by the system
        /// </summary>
        public string OTP { get; set; }
    }
}
